### ISSUE TITLE
Add individual border control and 0 px gaps

### ISSUE THREAD

**Issue by joelostblom** [necropolina/gnome-edge-gap#2]
Thank you so much for mentioning this over at the popOS issue thread! Your extension really alleviates the problem and the 1 pixel gap on top is much better than the default PopOS gap.

Would you be interested in adding the possibility to adjust gaps individually if it is not too involved? I would like to set all gaps to 0 px except the one on top of the screen. I could also try to fork this and only keep the top panel, but I haven't built any gnome extensions before so thought I would check in with your first.

**Comment by hobgoblina** [comment]
Glad to see somebody else found it useful 😄 I actually thought about doing individually-controllable sides after finishing up the current version - will plan on getting to it soon since there's interest. Should be able make the change on Saturday if not sometime during the week.

**Comment by joelostblom** [comment]
Wohoo! Thank you! I just noticed that your extension fixes another issue as well.

I use the tiled layout in the Pop Shell, and usually when I switch between my laptop screen and ultrawide external monitor, the tiling manager doesn't automatically detect that the resolution has changed (so they either extend beyond the screen size of my laptop, or not all the way to the edge of my external monitor). To correct this, I usually have to untile and retile all windows which loses the information on which windows are stacked together so that I need to manually go through and drag them on top of each other again.

Now that I have your extension installed, the tiled layout automatically snaps to the correct size when I switch monitor which is a nice quality of life improvement =) Maybe I will write Pop support a ticket to take some hints from your extensions and get this right by default...

**Comment by hobgoblina** [comment]
Awesome!! Wasn't aware of that bug. Yeah it seems like they just need trigger resizes in a couple places that might've been overlooked. Haven't peeked at their code yet tho (and not super familiar with the ins and outs of gnome shell in general), so not entirely sure what that'll entail.

**Comment by hobgoblina** [comment]
Submitted the new version to extensions.gnome.org for review. Should be available soon :smile:

**Comment by hobgoblina** [comment]
Looks to be active now!

**Comment by joelostblom** [comment]
Works perfectly, thank you so much!
